### ISSUE TITLE
list out of range

### ISSUE THREAD

**Issue by daniel41wq** [nicklien88/FacebookCrawler#1]
when I'm running the script I get the error list out of range

**Comment by nicklien88** [comment]
I'm sure where is wrong. Can you tell me values you type on GUI. I want to run the program.

**Comment by daniel41wq** [comment]
url : https://www.facebook.com/nike/
date 2020-03-01 to 2020-03-30
like: 1000
name: nike

**Comment by nicklien88** [comment]
I can run the program with these values. I think the reason of the error "list of out range" is the page's not finish loading at the time. I already wrote a while loop if it happens. Usually after it repeats couple times, it will resolve the error. If not, I suggest to restart the program.
